#!/usr/bin/env bash
# Reads the passed file as argument and print factors

MY_FILE=$1

while read MY_NUM
do
    factors=($(factor $MY_NUM))
    echo "$MY_NUM=$(($MY_NUM/${factors[1]}))*${factors[1]}"
done < $MY_FILE