#!/usr/bin/python3
from math import sqrt
from sys import argv


def factor():
    """ Factor function """
    with open(argv[1]) as file:
        for my_line in file:
            number = int(my_line)
            print("{:d}=".format(number), end="")
            if number % 2 == 0:
                print("{}*2".format(number//2))
                continue
            sqn = int(sqrt(number))
            if sqn % 2 == 0:
                sqn += 1
            for i in range(3, sqn + 1, 2):
                if number % i == 0:
                    print("{}*{}".format(i, number//i))
                    break
            if number % i != 0:
                print("{}={}*1".format(number, number))

factor()
